### ISSUE TITLE
I has an problem

### ISSUE THREAD

**Issue by TheTezma** [zachrip/MCJackpotBot#1]
Everytime I try to run index.js this appears

module.js:339
    throw err;
    ^

Error: Cannot find module './config'
    at Function.Module._resolveFilename (module.js
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\User\Desktop\M
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:44
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

**Comment by zachrip** [comment]
@TheTezma You need to name a file config.js and export your config.
